### ISSUE TITLE
CLI fail to compile when config has key `columns`

### ISSUE THREAD

**Issue by rick0000** [dataform-co/dataform#1233]
CLI fail to compile the example below, which config has key `columns`
```
config { type: "table",
         description: "This table is an example",
         columns:{
             user_name: "Name of the user",
             user_id: "ID of the user"
         } 
}

select
  1 as user_name,
  1 as user_id
```

But the following example will compile successfully
```
config { type: "table",
         description: "This table is an example",
}
select
  1 as user_name,
  1 as user_id
```

dataform version: 1.19.0

**Comment by nrodri86** [comment]
We have the same issue. We are using jenkins for CI/DEVOPS and we decided to remove the columns params to continue with our pipeline. We also notice the issue on slack but we haven´t received a feedback. :(

**Comment by BenBirt** [comment]
I can't reproduce this. Can you show me an example file (in the Dataform app), or give me other reproduction instructions? 

I've created a test project here, and the file as pasted above seems to compile just fine: https://app.dataform.co/#/4804174521827328/b/benbirt_dev/file/definitions%2Ftest.sqlx

**Comment by nrodri86** [comment]
Hello Ben. Did you compile or run the project using cli (https://docs.dataform.co/dataform-cli)? The problem is presented whe we use the cli commands.

**Comment by vvalcristina** [comment]
Hi @BenBirt in Dataform Web compiled to sucess:

![Captura de tela de 2021-06-28 12-05-49](https://user-images.githubusercontent.com/52939036/123659566-36c33480-d809-11eb-90d7-816d7303b22d.png)

However in Dataform CLI it presents the following error:  Compilation errors:
  definitions/reports/brasil_sales_report.sqlx: TypeError: Object.keys(...).map(...).flat is not a function
    at Function.mapToColumnProtoArray (/home/valeria.silva/DNA/Dataform-CLI/node_modules/@dataform/core/bundle.js:21740:14)
    at Table.columns (/home/valeria.silva/DNA/Dataform-CLI/node_modules/@dataform/core/bundle.js:22187:65)
    at Table.config (/home/valeria.silva/DNA/Dataform-CLI/node_modules/@dataform/core/bundle.js:22076:18)
    at Session.sqlxAction (/home/valeria.silva/DNA/Dataform-CLI/node_modules/@dataform/core/bundle.js:23400:22)
    at /home/valeria.silva/DNA/Dataform-CLI/definitions/reports/brasil_sales_report.sqlx:1:86
    at Object.EXTENSIONS.(anonymous function) [as .sqlx] (/usr/local/lib/node_modules/@dataform/cli/node_modules/vm2/lib/sandbox.js:91:5)
    at _require (/usr/local/lib/node_modules/@dataform/cli/node_modules/vm2/lib/sandbox.js:406:24)
    at Object.<anonymous> (/home/valeria.silva/DNA/Dataform-CLI/index.js:41:13)
    at NodeVM.run (/usr/local/lib/node_modules/@dataform/cli/node_modules/vm2/lib/main.js:1167:29)
    at compile$1 (/usr/local/lib/node_modules/@dataform/cli/worker_bundle.js:20977:23)
    
![Captura de tela de 2021-06-28 12-05-26](https://user-images.githubusercontent.com/52939036/123659717-5b1f1100-d809-11eb-88e4-10be59e288b9.png)

It code I'm using is in the following repository(https://github.com/vvalcristina/Dataform-Jenkins-CLI/blob/feat/column/definitions/reports/brasil_sales_report.sqlx) on the branch feat/column

**Comment by BenBirt** [comment]
Apologies for the late reply here, my GitHub notifications weren't set up right!

@vvalcristina thanks a lot for the repo link. However, I still can't reproduce using the CLI:

```
➜  Code git clone git@github.com:vvalcristina/Dataform-Jenkins-CLI.git
Cloning into 'Dataform-Jenkins-CLI'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 43 (delta 10), reused 34 (delta 5), pack-reused 0
Receiving objects: 100% (43/43), 7.75 KiB | 1.29 MiB/s, done.
Resolving deltas: 100% (10/10), done.
➜  Code cd Dataform-Jenkins-CLI 
➜  Dataform-Jenkins-CLI git:(master) git checkout feat/column
Branch 'feat/column' set up to track remote branch 'feat/column' from 'origin'.
Switched to a new branch 'feat/column'
➜  Dataform-Jenkins-CLI git:(feat/column) dataform install
Installing NPM dependencies...


Project dependencies successfully installed.
➜  Dataform-Jenkins-CLI git:(feat/column) ✗ dataform compile
Compiling...

Compiled 2 action(s).
1 dataset(s):
  dataform.brasil_sales_report [view]
1 assertion(s):
  dataform_assertions.dataform_brasil_sales_report_assertions_rowConditions
```

Can you make sure you've (1) fully updated your project dependencies (`dataform install` in the project directory) and (2) fully updated `dataform` (rerun `npm install -g @dataform/cli`)?
