### ISSUE TITLE
When `dataform init` fails, files are still written, preventing a second `dataform init`

### ISSUE THREAD

**Issue by dwl285** [dataform-co/dataform#1243]
When dataform init fails, the files are still created even though an error message is shown. The error message suggests you should run `dataform init` a second time, but when you do, it fails. This is a confusing user experience very early in starting to use the product.

Steps to reproduce:
1. Run `dataform init bigquery new_project`
Error: 
```
leeda@leeda:~/dataform$ dataform init bigquery new_project
Dataform encountered an error: The --default-database flag is required for BigQuery projects. Please run 'dataform help init' for more information.
Writing project files...

Error: The --default-database flag is required for BigQuery projects. Please run 'dataform help init' for more information.
    at check (/usr/local/lib/node_modules/@dataform/cli/bundle.js:27202:39)
    at /usr/local/lib/node_modules/@dataform/cli/bundle.js:26837:33
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/@dataform/cli/bundle.js:26837:16
    at Object.customChecks (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:1572:26)
    at Object.runValidation [as _runValidation] (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:2826:22)
    at Object.runCommand (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:434:19)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:2697:57)
    at Object.get [as argv] (/usr/local/lib/node_modules/@dataform/cli/node_modules/yargs/build/index.cjs:2651:25)
    at runCli (/usr/local/lib/node_modules/@dataform/cli/bundle.js:27636:7)
```

2. Try rerunning, this time including the default-database flag: `dataform init bigquery new_project --default-database project-id`
Error:
```
leeda@leeda:~/dataform$ dataform init bigquery new_project --default-database project-id
Writing project files...

Dataform encountered an error: Cannot init dataform project, this already appears to be an NPM or Dataform directory.
Error: Cannot init dataform project, this already appears to be an NPM or Dataform directory.
    at init (/usr/local/lib/node_modules/@dataform/cli/bundle.js:25810:15)
    at Object.processFn (/usr/local/lib/node_modules/@dataform/cli/bundle.js:27230:46)
    at Object.handler (/usr/local/lib/node_modules/@dataform/cli/bundle.js:26810:44)
```

**Comment by Ekrekr** [comment]
```
$ dataform init bigquery new_project
Dataform encountered an error: The --default-database flag is required for BigQuery projects. Please run 'dataform help init' for more information.
Error: The --default-database flag is required for BigQuery projects. Please run 'dataform help init' for more information.
```

```
$ dataform init bigquery new_project --default-database project-id --default-location=us-central1
Writing project files...

Directories successfully created:
  /tmp/new_project
  /tmp/new_project/definitions
  /tmp/new_project/includes
Files successfully written:
  /tmp/new_project/dataform.json
  /tmp/new_project/package.json
  /tmp/new_project/.gitignore
NPM packages successfully installed.
```
