### ISSUE TITLE
CLI parse Json : Dataform encountered an error: Unexpected token (2:15)

### ISSUE THREAD

**Issue by vvalcristina** [dataform-co/dataform#1309]
Hello,

Intermittent error running tests through the CLI. In some executions there is a problem parsing the .df-credentials.json file.
Has anyone had this same problem?

```
+ set +x
Compiling...

[91mDataform encountered an error: Unexpected token (2:15)[0m
[91mSyntaxError: Unexpected token (2:15)
    at Parser.pp$4.raise (/home/jenkins/.npm-global/lib/node_modules/@dataform/cli/node_modules/acorn/dist/acorn.js:3460:15)
    at Parser.pp$9.unexpected (/home/jenkins/.npm-global/lib/node_modules/@dataform/cli/node_modules/acorn/dist/acorn.js:756:10)
    at Parser.pp$9.semicolon (/home/jenkins/.npm-global/lib/node_modules/@dataform/cli/node_modules/acorn/dist/acorn.js:733:68)
    at Parser.pp$8.parseExpressionStatement (/home/jenkins/.npm-global/lib/node_modules/@dataform/cli/node_modules/acorn/dist/acorn.js:1216:10)
    at Parser.pp$8.parseStatement (/home/jenkins/.npm-global/lib/node_modules/@dataform/cli/node_modules/acorn/dist/acorn.js:949:26)
    at Parser.pp$8.parseBlock (/home/jenkins/.npm-global/lib/node_modules/@dataform/cli/node_modules/acorn/dist/acorn.js:1232:23)
    at Parser.pp$8.parseStatement (/home/jenkins/.npm-global/lib/node_modules/@dataform/cli/node_modules/acorn/dist/acorn.js:914:38)
    at Parser.pp$8.parseTopLevel (/home/jenkins/.npm-global/lib/node_modules/@dataform/cli/node_modules/acorn/dist/acorn.js:813:23)
    at Parser.parse (/home/jenkins/.npm-global/lib/node_modules/@dataform/cli/node_modules/acorn/dist/acorn.js:586:17)
    at Function.parse (/home/jenkins/.npm-global/lib/node_modules/@dataform/cli/node_modules/acorn/dist/acorn.js:636:37)[0m
```

**Comment by ldolberg** [comment]
Please bump to the latest version, the fix has been released today.

**Comment by BenBirt** [comment]
That's correct - please use `1.21.1`.
