### ISSUE TITLE
Use of external NPM packges in a Dataform project

### ISSUE THREAD

**Issue by giksy101** [dataform-co/dataform#1394]
Hello @BenBirt and team,

we are trying to utilize external pakckages like (npm install fs, npm install js-yaml) to be able to read .yaml content into Dataform project. I am able to see compilation errors when I run "dataform compile ." as below. Is this possible at all to use other npm packages in a Dataform project? if yes, any pointers pls.
``Compilation errors:
  definitions/read.js: VMError: Cannot find module '/home/krgav/repos/npm_package_issue/dataform_package_issue/node_modules/fs'
    at DefaultResolver.loadAsPackage (/usr/lib/node_modules/@dataform/cli/node_modules/vm2/lib/resolver.js:428:11)
    at DefaultResolver.loadAsDirectory (/usr/lib/node_modules/@dataform/cli/node_modules/vm2/lib/resolver.js:440:15)
    at DefaultResolver.loadNodeModules (/usr/lib/node_modules/@dataform/cli/node_modules/vm2/lib/resolver.js:458:13)
    at DefaultResolver.resolveFull (/usr/lib/node_modules/@dataform/cli/node_modules/vm2/lib/resolver.js:311:12)
    at DefaultResolver.resolve (/usr/lib/node_modules/@dataform/cli/node_modules/vm2/lib/resolver.js:105:15)
    at ReadOnlyHandler.apply (/usr/lib/node_modules/@dataform/cli/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/usr/lib/node_modules/@dataform/cli/node_modules/vm2/lib/setup-node-sandbox.js:84:28)
    at require (/usr/lib/node_modules/@dataform/cli/node_modules/vm2/lib/setup-node-sandbox.js:165:10)
    at /home/krgav/repos/npm_package_issue/dataform_package_issue/index.js:1:88
    at VM2 Wrapper.apply (/usr/lib/node_modules/@dataform/cli/node_modules/vm2/lib/bridge.js:485:11)``

**Comment by BenBirt** [comment]
Dataform project compilation is [designed](https://docs.dataform.co/guides/sqlx#sandboxing-for-fast-secure-reproducible-sqlx-compilation) to prevent arbitrary access to disk.

However, you should be able to achieve what you want by using JSON - you can then `require("file.json")` as normal.
