### ISSUE TITLE
Dataform CLI is not working

### ISSUE THREAD

**Issue by Oscar-Rod** [dataform-co/dataform#1479]
I installed it running

sudo npm i -g @dataform/cli

And when I try to run it, I get the following:

`let uuidFunction = typeof ((_a = globalThis === null || globalThis === void 0 ? void 0 : globalThis.crypto) === null || _a === void 0 ? void 0 : _a.randomUUID) === "function"
                   ^

ReferenceError: globalThis is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/@dataform/cli/node_modules/@azure/core-util/dist/index.js:241:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@dataform/cli/node_modules/@azure/core-rest-pipeline/dist/index.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)`

**Comment by BenBirt** [comment]
Hm, I can't reproduce this.

Can you add some more reproduction instructions? What environment are you running this in? Have you already got a Dataform project, or are you creating a new one? What command are you running?
