### ISSUE TITLE
ReferenceError: javascript-functions is not defined

### ISSUE THREAD

**Issue by davidedironza** [dataform-co/dataform#1486]
Hi

**dataform CLI version: 2.4.2**

I have a simple dataform project with a js function in the folder "includes" and a view config in folder "definitions"

│   dataform.json
│   package-lock.json
│   package.json
├───definitions
│       dataform_test.sqlx
├───includes
│       get_current_datetime_ch.js

When I execute "dataform compile" with the CLI I get an **ReferenceError** and the functions within "includes" are not used.
```bash
  Compilation errors:
  definitions\dataform_test.sqlx: ReferenceError: get_current_datetime_ch is not defined
    at Object.sqlContextable (C:\Users\C203580\git_repository\gcp-helper-davide\dataform\davide\definitions\dataform_test.sqlx:21:7)
    at C:\Users\C203580\git_repository\gcp-helper-davide\dataform\davide\node_modules\@dataform\core\bundle.js:23830:49
    at TableContext.apply (C:\Users\C203580\git_repository\gcp-helper-davide\dataform\davide\node_modules\@dataform\core\bundle.js:22703:20)
    at Table.compile (C:\Users\C203580\git_repository\gcp-helper-davide\dataform\davide\node_modules\@dataform\core\bundle.js:22593:36)
    at C:\Users\C203580\git_repository\gcp-helper-davide\dataform\davide\node_modules\@dataform\core\bundle.js:24011:46
    at Array.forEach (<anonymous>)
    at Session.compileGraphChunk (C:\Users\C203580\git_repository\gcp-helper-davide\dataform\davide\node_modules\@dataform\core\bundle.js:24009:17)
    at Session.compile (C:\Users\C203580\git_repository\gcp-helper-davide\dataform\davide\node_modules\@dataform\core\bundle.js:23974:26)
    at Object.main (C:\Users\C203580\git_repository\gcp-helper-davide\dataform\davide\node_modules\@dataform\core\bundle.js:24367:127)
    at C:\Users\C203580\git_repository\gcp-helper-davide\dataform\davide\index.js:1:96
```

**dataform_test.sqlx**
```sqlx
config {
  type: "view", // Creates a view in BigQuery. Try changing to "table" instead.
}

SELECT
    ${get_current_datetime_ch.get_current_datetime_ch()} as parm_01_ts_01
```

**get_current_datetime_ch.js**
```javascript
function get_current_datetime_ch() {

  return "DATETIME(TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(CURRENT_TIMESTAMP()), 60) * 60), 'Europe/Zurich')";
}

module.exports = {
  get_current_datetime_ch,
};
```

**Comment by davidedironza** [comment]
I found out that the issue is on windows.
On WSL (or Linux) it works as expected.

**Comment by davidedironza** [comment]
There is already an issue tracked on google site.
https://issuetracker.google.com/issues/279506026

As workaround I modified the related function in the node_module "...\node_modules\@dataform\core\bundle.js":
```js
const pathSeperator = (() => {
    if (typeof process !== "undefined") {
        return process.platform === "win32" ? "/" : "/";
    }
    return "/";
})();
```

**Comment by khanetor** [comment]
I am facing this issue as well, so I don't think you should close this, as this is clearly a bug.
