### ISSUE TITLE
Can we use promise in js blocks or .js files ?

### ISSUE THREAD

**Issue by vl4py** [dataform-co/dataform#1547]
Hi,

We are migrating code to dataform and we need to:
* Make a call to bigquery API to get a list of columns
* Use list of column to replace within a SQL query template
* Execute the SQL query

We tried two alternatives:

### Code
```
config {
    type: "table",
    disabled: false,
    hasOutput: true,
    description: "This table contains sales orders",
    tags: ["dedup_test"]
}

js {
   const common = require("our_custom_lib");
   const deduplicationRequest = new common.deduplication.DeduplicationRequest(someRequestParameters...);

   async function output() {
       return await dedup.getDeduplicationRequest(deduplicationRequest)
   }
}

${output().then(res => res)}
```
### Output
```
Compiling...

Compiled successfully.

Running...

Operation failed:  dataform.dedup_test
  > 
  > 
  > 
  > 
  > [object Promise]
  bigquery error: Syntax error
```  
### Code

```
const common = require("our_custom_lib");

const params = {
    database: "our_database",
    schema: "dataform",
    type: "table",
    disabled: false,
    description: "This table contains sales orders",
    tags: ["dedup_test"]
}

async function executeQuery(params) {
    (async () => {
            const deduplicationRequest = new common.deduplication.DeduplicationRequest(someRequestParameters...)
             // Our async logic using bigquery JS client
            return await common.deduplication.getDeltaDeduplicationQuery(deduplicationRequest)
        }
    ).then( dedupQuery => {
            // dataform-core
            publish("transactions",params).query(dedupQuery);
        }
    )
}

executeQuery(params);
```
### Output
Compilation runs fine but the table does not appear in compiled tables.

# Question

Is it possible to use such async logics where we need to interact with BQ API ?

**Comment by jbrown-xentity** [comment]
I'd like to second this problem. I have tried to install `@google-cloud/bigquery`, both in the GCP UI and locally. Whenever I try to require it (`const { BigQuery } = require('@google-cloud/bigquery');`), I get the following error. It might be related to https://github.com/dataform-co/dataform/issues/1615.

I want to be able to scan a dataset, and compare the tables to ones with the same name in another dataset (think staging and prod environments). But the moment I try to use BigQuery library, it fails. I even tried with `fs` library, same problem. Using dataform version `2.7.0`, with node `v20.10.0`

```
  Compilation errors:
  includes/assertions.js: VMError: Cannot find module 'events'
    at CustomResolver.resolveFull (/home/jamesbrown/.nvm/versions/node/v20.10.0/lib/node_modules/@dataform/cli/node_modules/vm2/lib/resolver.js:126:9)
    at CustomResolver.resolveFull (/home/jamesbrown/.nvm/versions/node/v20.10.0/lib/node_modules/@dataform/cli/node_modules/vm2/lib/resolver.js:316:16)
    at CustomResolver.resolve (/home/jamesbrown/.nvm/versions/node/v20.10.0/lib/node_modules/@dataform/cli/node_modules/vm2/lib/resolver.js:121:15)
    at resolve (/home/jamesbrown/.nvm/versions/node/v20.10.0/lib/node_modules/@dataform/cli/node_modules/vm2/lib/nodevm.js:317:21)
    at VM2 Wrapper.apply (/home/jamesbrown/.nvm/versions/node/v20.10.0/lib/node_modules/@dataform/cli/node_modules/vm2/lib/bridge.js:485:11)
    at requireImpl (/home/jamesbrown/.nvm/versions/node/v20.10.0/lib/node_modules/@dataform/cli/node_modules/vm2/lib/setup-node-sandbox.js:90:19)
    at require (/home/jamesbrown/.nvm/versions/node/v20.10.0/lib/node_modules/@dataform/cli/node_modules/vm2/lib/setup-node-sandbox.js:171:10)
    at /home/jamesbrown/cdot/domain-mart-hr/node_modules/@google-cloud/common/build/src/service-object.js:22:18
    at VM2 Wrapper.apply (/home/jamesbrown/.nvm/versions/node/v20.10.0/lib/node_modules/@dataform/cli/node_modules/vm2/lib/bridge.js:485:11)
    at NodeVM.run (/home/jamesbrown/.nvm/versions/node/v20.10.0/lib/node_modules/@dataform/cli/node_modules/vm2/lib/nodevm.js:497:23)
```

**Comment by BenBirt** [comment]
Thanks for filing this issue, apologies for missing it.

I think there is some confusion here in a few different places.

1) Dataform compilation is (by design) sandboxed from the outside world. Dataform code cannot make network calls (e.g. the BigQuery API) nor (arbitrarily) access the filesystem.
2) Dataform compilation is not designed to be 100% compatible with all nodejs packages. That said, as long as we don't break the invariant described in (1), we are open to improving the compilation environment to improve compatibility where an issue exists.

The reasoning for (1) is:
- it ensures that the same version of code will always produce the same output SQL, i.e. it ensures that output is *reproducible*
- it ensures that compilation times stay fast
