### ISSUE TITLE
dataform-cli compile throws errors that web UX does not

### ISSUE THREAD

**Issue by justinaugust** [dataform-co/dataform#1874]
Trying to enable the use of VSCode for my org.
I'm getting compile errors in my codebase on the CLI that I am not getting on the web UX.

cli and web v2.9.0

**Comment by kolina** [comment]
Can you show an error that you're getting?

**Comment by justinaugust** [comment]
> Can you show an error that you're getting?
These all have conditional `whereClause` I believe.
What's failing is when it is set to
```
      whereClause = ``
```
But this does not and has never failed in the webGUI


```
  Compilation errors:
  definitions/pg_tables/assertions/pg_historical_schedules_uniqueKey_daily.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:120:19)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_historical_schedules_uniqueKey_daily.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_historical_schedules_uniqueKey_hourly.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:118:21)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_historical_schedules_uniqueKey_hourly.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_load_corpus_entry_uniqueKey_daily.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:120:19)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_load_corpus_entry_uniqueKey_daily.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_load_corpus_entry_uniqueKey_hourly.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:118:21)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_load_corpus_entry_uniqueKey_hourly.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_load_flags_uniqueKey_daily.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:120:19)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_load_flags_uniqueKey_daily.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_load_flags_uniqueKey_hourly.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:118:21)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_load_flags_uniqueKey_hourly.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_load_recommendation_scores_uniqueKey_daily.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:120:19)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_load_recommendation_scores_uniqueKey_daily.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_load_recommendation_scores_uniqueKey_hourly.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:118:21)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_load_recommendation_scores_uniqueKey_hourly.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_load_stop_flags_uniqueKey_daily.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:120:19)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_load_stop_flags_uniqueKey_daily.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_load_stop_flags_uniqueKey_hourly.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:118:21)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_load_stop_flags_uniqueKey_hourly.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_loads_uniqueKey_daily.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:120:19)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_loads_uniqueKey_daily.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_loads_uniqueKey_hourly.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:118:21)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_loads_uniqueKey_hourly.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_location_vectors_uniqueKey_daily.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:120:19)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_location_vectors_uniqueKey_daily.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_location_vectors_uniqueKey_hourly.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:118:21)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_location_vectors_uniqueKey_hourly.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_query_searches_uniqueKey_daily.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:120:19)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_query_searches_uniqueKey_daily.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_query_searches_uniqueKey_hourly.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:118:21)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_query_searches_uniqueKey_hourly.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_schedule_events_uniqueKey_daily.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:120:19)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_schedule_events_uniqueKey_daily.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_schedule_events_uniqueKey_hourly.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:118:21)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_schedule_events_uniqueKey_hourly.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_schedules_uniqueKey_daily.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:120:19)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_schedules_uniqueKey_daily.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
  definitions/pg_tables/assertions/pg_schedules_uniqueKey_hourly.sqlx: ReferenceError: whereClause is not defined
    at Object.pgAssertion (/Users/jaugust/dev/dataform-analytics/includes/utils.js:118:21)
    at Object.sqlContextable (/Users/jaugust/dev/dataform-analytics/definitions/pg_tables/assertions/pg_schedules_uniqueKey_hourly.sqlx:23:9)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:383654
    at o.apply (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:285734)
    at t.Assertion.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:284693)
    at /Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:389014
    at Array.forEach (<anonymous>)
    at t.Session.compileGraphChunk (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:388988)
    at t.Session.compile (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:387286)
    at t.main (/Users/jaugust/dev/dataform-analytics/node_modules/@dataform/core/bundle.js:1:380350)
```

But then I fixed it by pre-declaring the variable. This fixed it for the CLI compilation. But the behavior should match across clients.
