### ISSUE TITLE
Projects sometimes failing to compile

### ISSUE THREAD

**Issue by BenBirt** [dataform-co/dataform#325]
```
Error: Unable to compile project: Error: ENOENT: no such file or directory, unlink '/var/folders/mc/tv7mxfn90hb07gzt87b92_7w0000gn/T/dataform/caab6986193fd9b2b2d26edafa750ddf'
    at Object.unlinkSync (fs.js:949:3)
    at compileInTmpDir (external/df/api/vm/compile.ts:103:8)
```

**Comment by faiyaz26** [comment]
Could not find similar error on production server. So closing it for now, will reopen if we see this kind of error on production.
