### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined at cleanRows

### ISSUE THREAD

**Issue by lewish** [dataform-co/dataform#384]
```
TypeError: Cannot read property 'length' of undefined at cleanRows (/external/df/api/dbadapters/bigquery.ts:214:12) at job.getQueryResults (/external/df/api/dbadapters/bigquery.ts:192:21)
```

This causes a `cannot read property value of null` error in the IDE.

**Comment by BenBirt** [comment]
Closing as duplicate
